name: Python application

on: [push, pull_request]
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pipenv dependencies
      run: |
        pip install pipenv
        pipenv install --dev
        pipenv shell
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --rcfile=.pylintrc api
    - name: Test with pytest
      run: |
        pip install pytest
        pytest